#sudo: true
#dist: trusty
language: php
php:
  - 7.0

env:
  - secure: gIGVQIJrOUgl2FuxUXer9FMBDSj+YqH7SiuNVXmZDy4krfQfrdMN/3oRQpIuPjYporjwi6Y31kppmW/d92WKB7JUJ+oWhhnUN0kDU23oVC2RsSIj6ic4rT08N0fYUEHEg77P+E+oX85lRLtr90HJN+jA2o+MHy3ACkaQWt9LVgsX7nu2IOl3ZCFecaCyNWidr0kKFDxQ15eh6kN5xXtDB0jnxPv9Ghf4chjgDzcTYsfhnuHbUfvEsJCRPdBc8itjEpYuA+QPziRxp4nQaRwiG/ltoUfbhuZiUZrctD58Y/a6N8cxEkQjJyJGV+BfUjYdu9ZRzwOVOYZsUbOktAwoPUESm0BLZylnNWUkBs6CjELQ7yCFJmu9vIu4CoOIrbjw3OqY6ZSdItV3HrfbPWC7tOsXCHqscUVvPUgKK5un8psZdFZltijs7lHS4qjj1B25uBvB+rGFk4lvFfUsR4lf3RGW2/xSIEg+QxMc4hmriE7b0YLTUfAVxBIT4EnTpAQoS+jrIv6Lrg9FTc8s1L7UA0Re10XrbRb4+dfkVGnttRvpZlh7yF/gWH30gfprpmCnropqNjtqxfUlRn6AgOS5xo8kl/ov+aYSe8M3T7dWW51S3rrPpCiNTVBm2udPRmtu0VK2Eh4804dYeVOiJo4j5cpFfzC7J7BbIWS9ETSsxUk=
  - secure: l/SEM1wlduHGUifShMmVm1kpOeQavz/rTPsAid2KPY0v86HpLTxrBFHmZMF2m8cKYE4SmRIHj7e/QO3nO1a5qIeuvl8HFsm0NAzl8KmOkzrDx0EDmHvWyFf3bhN/DkDxueuLWyqcqP9H/PG0MxOvxHMCKfkX6afHLtG3Ps0j8I9HCKBkSZfbbTdKIAaRpVZ580ufJvDlVFNIyeSx8CtZA7jKMaRH9rIyE858o7N9qBKARlqzwv/W0prG3Vq3UZqQ6qMwdoRE3sVO8XNf/RoaGJsBwz6yWqSgOeV6GUvbn85nhT2DUNJ9fAipylx2feC86BS3CTvcYxhA3K4DDOUFCiV9T/e5W4Lagn1zTP8YrFvNoUvQUV4mET/FsSmstHvoM6t15v2Qd2XeUHpIYvm6lsgKTMGOIpSYzIERuHuY/5t/ZxkXIsRNhjDAjdAu6iqLDXZwxERrOfHRZq5Dr7jGrGlckUE2VFMs+qe0G9WaTwWoS6yUIMfSEUBRB2x1OhfEyjgwj0PJY7gjf5LiwU/ZTg/m3dEP2WSQ2xWsTqKRSBOqeo4B2GGJLIWsm/ylBA8Q1lSfrWzgG6tIEB4LO1JgSbYcGtBMupD/4r05CjwGjW9VK3zE1LljcqCqRp5U1eESpbjnH0k1U+U7JIXeN2djo2D31DtD/uYe3RF08k25sas=
  - TRAVIS_NODE_VERSION="7"
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - graphicsmagick

before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
- export PATH=$HOME/.yarn/bin:$PATH
- composer global require hirak/prestissimo
- if [[ -n "$GITHUB_TOKEN" ]]; then composer config -g github-oauth.github.com ${GITHUB_TOKEN};
  fi;

before_script:
- phpenv config-rm xdebug.ini

install:
- npm install gulpjs/gulp-cli -g
- npm install gulpjs/gulp#4.0
- npm install --global now
- npm install --global lerna
- npm install && npm run bootstrap && npm run setup:composer

script:
- npm run test && npm run build

after_success:
- npm run deploy

cache:
  apt: true
  yarn: true
  directories:
  - "$HOME/.cache/yarn"
  - node_modules

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    secure: cNto+gWAoK1JM9jBNG4i4rMSybv3twMbqlFSCohQFBDMwKFMdlyWqFDX6iYKtHxWEDzrZyRz3qiJ8/S44mgjeKJ/xHbHDtPchp/KL2P1htipvwD2EZXobcBEGl83v2rmtFO1WNJUPB3RIJE2yt1wJsX7NIXpDw82hePmaIvNJmtbLpK/J5uaFqGNHIsctmULgVmGSNSTyK4nYxxjNNLd0EvO37Y6VN8FhsKNu2NHMKeeQxinEvETDUh8XuqXZYNWE3PBvVa4OiDhgnr5K27jsnWX+wEmqg0xY+CMf7mUSTqVN61fA7LnHyM0qcGGmB6YTv4QYLMwPydp+nsjDcm3St9D+KOTsQ4ExOaEAL/6EnAEpl8GtxST+ytdqswhCC4yMCO61Hy+M5AoXgDSGrrXHgZakDMAcEVcJdH38791hRxcuM3ldVmHAlAWFdgRLG5rRMVh3qoXz7jbraoTdjyKMegQIQdKR2SX7O9Dv0EEtLz4lTFN2RENvAjLggUPPU+ESoUHmSbwmPGnt7jy3ra2AI3nnYpfn/0e6Op/A3z7HLbdm3XyuNWoTPhy1mc4Adca+HosJ37UPv7nDRIGds1sKYAeWq94+rEk+/6IQ/oRIDRhSYsQbLLWnU6DH4o7iOj7D+X/ngjqmF75nW2s5+7rtdBHFvNzOJalCKHiDTMfdlQ=
