dist: bionic
language: php
php:
  - 7.3

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
    - docs-site/cache
    - www
    - cache

# before_cache:
# - mkdir -p node_modules
# - mkdir -p docs-site/cache
# - mkdir -p cache
# - mkdir -p www

before_install:
  - openssl aes-256-cbc -K $encrypted_4537e53f71e7_key -iv $encrypted_4537e53f71e7_iv -in scripts/bolt-design-system-bot.private-key.pem.enc -out scripts/bolt-design-system-bot.private-key.pem -d
  - nvm install # version lifted from `.nvmrc`
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - composer config --global github-oauth.github.com ${GH_TOKEN}

stages:
  - Post-deploy

jobs:
  include:
    - stage: Post-deploy
      name: 'Nightwatch End-to-End (Full)'
      # if: (tag =~ ^v) OR (branch =~ /(master|release|bug|fix)/)
      install:
        - npx json -I -f package.json -e 'delete this.dependencies'
        - npx json -I -f package.json -e 'delete this.scripts.postinstall'
        - npx json -I -f package.json -e 'this["workspaces"].packages = ["scripts", "packages/testing/testing-nightwatch"]'
        - yarn install --production
      script:
        - export NOW_URL=$(./scripts/get-latest-deploy.js)
        - travis_retry yarn run test:e2e:full
      after_success:
        - ./scripts/deploy-branch-alias.js
        - ./scripts/deploy-tagged-release.js
        # - ./packages/testing/testing-nightwatch/nightwatch-report-results.js

notifications:
  email:
    on_success: never
    on_failure: true # @todo re-enable
  slack:
    secure: cNto+gWAoK1JM9jBNG4i4rMSybv3twMbqlFSCohQFBDMwKFMdlyWqFDX6iYKtHxWEDzrZyRz3qiJ8/S44mgjeKJ/xHbHDtPchp/KL2P1htipvwD2EZXobcBEGl83v2rmtFO1WNJUPB3RIJE2yt1wJsX7NIXpDw82hePmaIvNJmtbLpK/J5uaFqGNHIsctmULgVmGSNSTyK4nYxxjNNLd0EvO37Y6VN8FhsKNu2NHMKeeQxinEvETDUh8XuqXZYNWE3PBvVa4OiDhgnr5K27jsnWX+wEmqg0xY+CMf7mUSTqVN61fA7LnHyM0qcGGmB6YTv4QYLMwPydp+nsjDcm3St9D+KOTsQ4ExOaEAL/6EnAEpl8GtxST+ytdqswhCC4yMCO61Hy+M5AoXgDSGrrXHgZakDMAcEVcJdH38791hRxcuM3ldVmHAlAWFdgRLG5rRMVh3qoXz7jbraoTdjyKMegQIQdKR2SX7O9Dv0EEtLz4lTFN2RENvAjLggUPPU+ESoUHmSbwmPGnt7jy3ra2AI3nnYpfn/0e6Op/A3z7HLbdm3XyuNWoTPhy1mc4Adca+HosJ37UPv7nDRIGds1sKYAeWq94+rEk+/6IQ/oRIDRhSYsQbLLWnU6DH4o7iOj7D+X/ngjqmF75nW2s5+7rtdBHFvNzOJalCKHiDTMfdlQ=
