sudo: required
dist: trusty

services:
  - docker

language: php
php:
  - 7.1

addons:
  sauce_connect: true

before_install:
# - nvm install # version lifted from `.nvmrc`
# - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
# - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
- phpenv config-rm xdebug.ini

install:
# - yarn run setup

before_script:
# - yarn run lint

# Can't do deploy on `after_success` b/c if deploy fails, the build still reports success. Can't use `deploy` step b/c Travis skips that on PRs.
script:
- docker pull boltdesignsystem/bolt || true
- docker build --pull --cache-from boltdesignsystem/bolt --tag boltdesignsystem/bolt .
- docker images
- echo $DOCKER_HUB_PASS | docker login --username $DOCKER_HUB_USER --password-stdin
- GIT_SHA="$(git rev-parse --short HEAD)"
- docker tag boltdesignsystem/bolt boltdesignsystem/bolt:latest
- docker tag boltdesignsystem/bolt boltdesignsystem/bolt:${GIT_SHA}
- docker push boltdesignsystem/bolt:latest && docker push boltdesignsystem/bolt:${GIT_SHA}
# - bash ./travis.sh # time command already run inside the travis.sh script
# - npx nightwatch@0.9.20 --config nightwatch.js --env chrome,ie11

after_script:
  - echo '' && echo 'About to deploy...' && echo ''
  - cd deploys && DOCKER_TAG=$GIT_SHA npx now deploy --force --team boltdesignsystem --token $NOW_TOKEN

cache:
  apt: true
  directories:
    - $HOME/.composer/cache/files

notifications:
  email:
    on_success: never
    on_failure: never # @todo re-enable
  slack:
    secure: cNto+gWAoK1JM9jBNG4i4rMSybv3twMbqlFSCohQFBDMwKFMdlyWqFDX6iYKtHxWEDzrZyRz3qiJ8/S44mgjeKJ/xHbHDtPchp/KL2P1htipvwD2EZXobcBEGl83v2rmtFO1WNJUPB3RIJE2yt1wJsX7NIXpDw82hePmaIvNJmtbLpK/J5uaFqGNHIsctmULgVmGSNSTyK4nYxxjNNLd0EvO37Y6VN8FhsKNu2NHMKeeQxinEvETDUh8XuqXZYNWE3PBvVa4OiDhgnr5K27jsnWX+wEmqg0xY+CMf7mUSTqVN61fA7LnHyM0qcGGmB6YTv4QYLMwPydp+nsjDcm3St9D+KOTsQ4ExOaEAL/6EnAEpl8GtxST+ytdqswhCC4yMCO61Hy+M5AoXgDSGrrXHgZakDMAcEVcJdH38791hRxcuM3ldVmHAlAWFdgRLG5rRMVh3qoXz7jbraoTdjyKMegQIQdKR2SX7O9Dv0EEtLz4lTFN2RENvAjLggUPPU+ESoUHmSbwmPGnt7jy3ra2AI3nnYpfn/0e6Op/A3z7HLbdm3XyuNWoTPhy1mc4Adca+HosJ37UPv7nDRIGds1sKYAeWq94+rEk+/6IQ/oRIDRhSYsQbLLWnU6DH4o7iOj7D+X/ngjqmF75nW2s5+7rtdBHFvNzOJalCKHiDTMfdlQ=

