v: 2.6.0
overrideConfig: q
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
  - scripts
  - styles
cleanPublic: false
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: ../dist
sourceDir: source
defaultPattern: pages-bolt-homepage
defaultShowPatternInfo: false
ishViewportRange:
  s:
    - 320
    - 600
  m:
    - 600
    - 1000
  l:
    - 1000
    - 2600
baseDir: /Users/sghoweri/sites/bolt/.pattern-lab/
ishControlsHide:
  - hay
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
lineageMatch: >-
  {%([ ]+)?(?:include|extends|embed)(
  |\()[&quot;\&#039;]([\/.@A-Za-z0-9-_]+)[&quot;\&#039;]([\s\S+]*?)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
extensions:
  data: .data.json
  schemas: .json
  templates: .twig
  docs: .docs.md
  sg: .md
plugins:
  twigNamespaces:
    enabled: true
    namespaces:
      bolt:
        paths:
          - source/_patterns/00-utils
          - source/_patterns/01-core/01-settings/settings-colors/demos
          - source/_patterns/01-core/01-settings/settings-colors/src
          - source/_patterns/01-core/02-tools/tools-spacing/demos
          - source/_patterns/01-core/04-elements/elements-headings
          - source/_patterns/01-core/04-elements/elements-links
          - source/_patterns/01-core/04-elements/elements-paragraphs
          - source/_patterns/01-core/04-elements/elements-small
          - source/_patterns/01-core/04-elements/elements-tables
          - source/_patterns/01-core/05-objects/bolt-bare-list-object/src
          - source/_patterns/01-core/05-objects/bolt-block-object/src
          - source/_patterns/01-core/05-objects/bolt-crop-object/src
          - source/_patterns/01-core/05-objects/bolt-flag-object/src
          - source/_patterns/01-core/05-objects/bolt-grid-object
          - source/_patterns/01-core/05-objects/bolt-inline-list-object/src
          - source/_patterns/01-core/05-objects/bolt-island-object/src
          - source/_patterns/01-core/05-objects/bolt-ratio-object/src
          - source/_patterns/01-core/05-objects/bolt-ui-list-object/src
          - source/_patterns/01-core/05-objects/bolt-wrapper-object/src
          - source/_patterns/02-components/bolt-action-blocks/src
          - source/_patterns/02-components/bolt-background/demo
          - source/_patterns/02-components/bolt-background/src
          - source/_patterns/02-components/bolt-band/demo
          - source/_patterns/02-components/bolt-band/src
          - source/_patterns/02-components/bolt-blockquote/demo/theming
          - source/_patterns/02-components/bolt-blockquote/src
          - source/_patterns/02-components/bolt-button-group/src
          - source/_patterns/02-components/bolt-button/demos
          - source/_patterns/02-components/bolt-button/src
          - source/_patterns/02-components/bolt-card/demo
          - source/_patterns/02-components/bolt-card/src
          - source/_patterns/02-components/bolt-chip-list
          - source/_patterns/02-components/bolt-chip/src
          - source/_patterns/02-components/bolt-headline/demo
          - source/_patterns/02-components/bolt-headline/demo/h1-through-h6
          - source/_patterns/02-components/bolt-headline/src
          - source/_patterns/02-components/bolt-icon/src
          - source/_patterns/02-components/bolt-image/src
          - source/_patterns/02-components/bolt-link
          - source/_patterns/02-components/bolt-logo/src
          - source/_patterns/02-components/bolt-ordered-list/demo/theming
          - source/_patterns/02-components/bolt-ordered-list/src
          - source/_patterns/02-components/bolt-page-footer/lib
          - source/_patterns/02-components/bolt-page-footer/src
          - source/_patterns/02-components/bolt-quote
          - source/_patterns/02-components/bolt-teaser/src
          - source/_patterns/02-components/bolt-unordered-list/demo/theming
          - source/_patterns/02-components/bolt-unordered-list/src
          - source/_patterns/03-templates/default
          - source/_patterns/04-pages/bolt-homepage
          - source/_patterns/04-pages/d8-homepage
          - source/_patterns/04-pages/d8-resource-details
    roots: {}
ishMinimum: '240'
ishMaximum: '2600'
