v: 2.6.0
overrideConfig: q
ie:
  - DS_Store
  - less
  - scss
id:
  - scss
  - .svn
  - .sass-cache
  - scripts
  - styles
  - images
cleanPublic: false
patternStates:
  - inprogress
  - inreview
  - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: export
publicDir: bolt-website
sourceDir: src
defaultPattern: 05-pages-bolt-homepage
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
  - hay
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
lineageMatch: >-
  {%([ ]+)?(?:include|extends|embed)(
  |\()[&quot;\&#039;]([\/.@A-Za-z0-9-]+)[&quot;\&#039;]([
  A-Za-z0-9-&\}_\n\{&quot;:\&#039;,\/. \[\]]+)%}
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
extensions:
  data: .data.json
  schemas: .json
  templates: .twig
  docs: .docs.md
  sg: .md
plugins:
  twigNamespaces:
    enabled: true
    namespaces:
      bolt:
        paths:
          - src/_patterns/01-core/01-settings/settings-colors/demos
          - src/_patterns/01-core/01-settings/settings-colors/src/twig
          - src/_patterns/01-core/02-tools/tools-spacing/demos
          - src/_patterns/01-core/04-elements/elements-headings
          - src/_patterns/01-core/04-elements/elements-images
          - src/_patterns/01-core/04-elements/elements-links
          - src/_patterns/01-core/04-elements/elements-paragraphs
          - src/_patterns/01-core/04-elements/elements-small
          - src/_patterns/01-core/04-elements/elements-tables
          - src/_patterns/02-components/01-images/components-image
          - src/_patterns/02-components/01-images/components-image/src
          - src/_patterns/02-components/01-images/logo/src
          - src/_patterns/02-components/action-block/lib
          - src/_patterns/02-components/action-block/src
          - src/_patterns/02-components/bands/demo
          - src/_patterns/02-components/bands/src
          - src/_patterns/02-components/buttons/01-button/demos
          - src/_patterns/02-components/buttons/01-button/src
          - src/_patterns/02-components/buttons/02-button-group/src
          - src/_patterns/02-components/cards/card/lib
          - src/_patterns/02-components/cards/card/src
          - src/_patterns/02-components/chips/components-chip-list
          - src/_patterns/02-components/chips/components-chip/lib
          - src/_patterns/02-components/chips/components-chip/src
          - src/_patterns/02-components/components-headline/demo
          - src/_patterns/02-components/components-headline/lib
          - src/_patterns/02-components/components-headline/src
          - src/_patterns/02-components/components-links
          - src/_patterns/02-components/components-lists/01-examples
          - src/_patterns/02-components/components-lists
          - src/_patterns/02-components/components-page-footer/lib
          - src/_patterns/02-components/components-page-footer/src
          - src/_patterns/02-components/components-quote
          - src/_patterns/02-components/components-teaser/src/twig
          - src/_patterns/02-components/layouts/objects-grid
          - src/_patterns/02-components/layouts/objects-inline-list/lib
          - src/_patterns/02-components/layouts/objects-inline-list/src
          - src/_patterns/02-components/layouts/objects-ratio
          - src/_patterns/02-components/layouts/objects-ui-list/demo
          - src/_patterns/02-components/layouts/objects-ui-list/lib
          - src/_patterns/02-components/layouts/objects-ui-list/src
          - src/_patterns/02-components/layouts/objects-wrapper/lib
          - src/_patterns/02-components/layouts/objects-wrapper/src
          - src/_patterns/03-templates/templates-default
          - src/_patterns/04-pages
