title: Pattern Kit


namespaces:
  includes: _includes
  layouts: _layouts
  patterns: ../../boltdesignsystem.com/templates
  # bolt: public/templates
paths:
  data:
    - ../../boltdesignsystem.com/data
  schemas:
    - ../../boltdesignsystem.com/schemas
  templates:
    - ../../boltdesignsystem.com/templates
  docs:
    - ../../boltdesignsystem.com/docs
  sg:
    - _content
extensions:
  data: .data.json
  schemas: .json
  templates: .twig
  docs: .docs.md
  sg: .md
categories:
    - Pattern
    - Component
    - Layout
assets:
  css:
    # - /source/styles/style.css
  js:
  footer_js:
